project:
  type: website

website:
  title: Data Dynamos
  navbar:
    right:
      - icon: github
        href: https://github.com/INFO526-DataViz/project-Data-Dynamos
    left:
      - text: Project
        href: index.qmd
      - text: Proposal
        href: proposal.qmd
      - text: Presentation
        href: presentation.qmd
      - text: About
        href: about.qmd
    logo: images\logo.jpg
  favicon: images\logo.jpg

format:
  html:
    theme: default
    toc: true

execute:
  freeze: auto
